### ISSUE TITLE
Ready for production

### ISSUE THREAD

**Issue by chaspy** [chaspy/ask-python#2]
## TODO
- [ ] Deploy to heroku from master https://github.com/chaspy/ask-python/pull/3
- [x] Set DNS record `ask.chaspy.me` https://github.com/chaspy/route53/pull/1
  - http://ask.chaspy.me is available!
- [x] Deploy to staging app https://github.com/chaspy/ask-python/issues/2#issuecomment-464311195
- [x] Heroku pipeline for production https://github.com/chaspy/ask-python/issues/2#issuecomment-464311907
- [ ] CircleCI (for testing / docker build and push) https://github.com/chaspy/ask-python/pull/7
  - for testing: #8 
- [x] Synthetic monitoring by Datadog https://app.datadoghq.com/synthetics/details/6sd-kj3-y23
- [x] Add papertrail addons as logging service

**Comment by chaspy** [comment]
## Staging app
Connect to github repo
<img width="1223" alt="screenshot 2019-02-16 17 06 25" src="https://user-images.githubusercontent.com/10370988/52896587-9fe41780-320d-11e9-9ac2-03d286cb0cdb.png">

Enable Review app
<img width="1227" alt="screenshot 2019-02-16 17 06 54" src="https://user-images.githubusercontent.com/10370988/52896590-a1addb00-320d-11e9-9c41-0117e0b44b92.png">
<img width="613" alt="screenshot 2019-02-16 17 08 48" src="https://user-images.githubusercontent.com/10370988/52896592-a3779e80-320d-11e9-845d-c0909b47fd8a.png">

Commit app.json
https://github.com/chaspy/ask-python/blob/master/app.json

**Comment by chaspy** [comment]
## Automate deploy to production
<img width="425" alt="screenshot 2019-02-16 17 13 13" src="https://user-images.githubusercontent.com/10370988/52896656-3b758800-320e-11e9-9702-8e91234ec8f5.png">
<img width="601" alt="screenshot 2019-02-16 17 13 24" src="https://user-images.githubusercontent.com/10370988/52896658-3ca6b500-320e-11e9-83c2-07ef4d1719b5.png">
<img width="606" alt="screenshot 2019-02-16 17 13 30" src="https://user-images.githubusercontent.com/10370988/52896663-3fa1a580-320e-11e9-8d47-c24d4e143e63.png">
